# Generated by Django 3.2.15 on 2022-09-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('context', models.TextField(blank=True, null=True, verbose_name='Context')),
                ('ref_answer', models.TextField(blank=True, null=True, verbose_name='Reference Answer')),
                ('stu_answer', models.TextField(blank=True, null=True, verbose_name='Student Answer')),
                ('auto_score_1', models.FloatField(blank=True, null=True, verbose_name='Automatic score 1')),
                ('auto_score_2', models.FloatField(blank=True, null=True, verbose_name='Automatic score 2')),
                ('auto_score_3', models.FloatField(blank=True, null=True, verbose_name='Automatic score 3')),
                ('marked_score', models.FloatField(blank=True, null=True, verbose_name='Marked Score')),
                ('student_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
