# Generated by Django 3.2.15 on 2022-09-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student_number',
        ),
        migrations.AddField(
            model_name='question',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student'),
        ),
    ]
